name: Merge Upstream

on:
  workflow_dispatch:
  
  schedule:
  - cron: "* * * * *"

jobs:
  merge-upstream:
    runs-on: self-hosted

    steps:
    - name: Clean
      run: rm -rf "${{ github.workspace }}"
    - uses: actions/checkout@v2
    - name: Add Remote
      run: git remote add -f upstream "https://github.com/nightscout/AndroidAPS"
    - name: Checkout
      run: git checkout master
    - name: Merge
      run: git merge --ff-only upstream/master
    - name: Push
      run: git push 
