name: Merge Upstream

on:
  workflow_dispatch:
  
  schedule:
  - cron: "* * * * *"

jobs:
  merge-upstream:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set upstream
      run: |
        git remote add -f upstream "https://github.com/nightscout/AndroidAPS.git"
        git checkout master
        git merge --ff-only upstream/master
        git push 
